### ISSUE TITLE
Search view theming

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#30]
The search view should be themed based on the toolbar light mode.
![screenshot_20160101-223250](https://cloud.githubusercontent.com/assets/11251606/12073103/c99d6faa-b0d7-11e5-9a9b-57e693c7d3b3.png)

**Comment by afollestad** [comment]
The text color/hint color and close button tint are now themed. All that's left is theming the icon to the left of the SearchView, which I'm assuming is the Toolbar's navigation icon.

Since it appears the Toolbar changes its own navigation icon when an ActionView expands, a reliable way to tint it is needed. I don't think relying on detecting when the SearchView is opened is a good way, since we don't want to override any of the user's listeners for the SearchView.

![screener_20160101 22-53-25](https://cloud.githubusercontent.com/assets/1820165/12073247/b19d562e-b0da-11e5-8552-022aeaec1b9c.png)
