### ISSUE TITLE
Ripple colors when tinting

### ISSUE THREAD

**Issue by AnimbusDev** [afollestad/app-theme-engine#31]
Can you please change the color of ripples from just black/white to the material colors?

https://github.com/afollestad/app-theme-engine/blob/90ef47177c0215137223c41b8d2d9d086dfd1201/library/src/main/java/com/afollestad/appthemeengine/util/TintHelper.java

**Comment by afollestad** [comment]
There's no reliable way to know which color to use from the Material spectrum, thus why white/black is used now.

The only reliable way to do that would be to lighten or darken the view color (based on the lightness of it) and use that result for the ripple.

But using white/gray for FAB ripples is pretty standard, which is why Cabinet for an example uses white for the ripple color.

**Comment by AnimbusDev** [comment]
@afollestad the color value can be found at ```
android.support.v7.appcompat.R.color.ripple_material_light ``` and  ```android.support.v7.appcompat.R.color.ripple_material_dark```

**Comment by afollestad** [comment]
Oh you meant the actual ripple defaults, I thought you meant the color palettes. Will do.

**Comment by AnimbusDev** [comment]
@afollestad on a side note, I don't think the way you tinted the icon in the fab would work pre 5.0

But I'm not sure

**Comment by afollestad** [comment]
@AnimbusDev it tends to work back to around ICS, I've already updated it to use the tinting other code in there uses (Drawable wrapping via AppCompat), I just haven't pushed quite yet
