### ISSUE TITLE
Optional dependencies (only import dependencies when they're used)?

### ISSUE THREAD

**Issue by afollestad** [afollestad/app-theme-engine#44]
I remember seeing that this was possible somewhere.

ATE imports CardView, the Support Design Library, my Material Dialogs library, etc.

For efficiency and space reasons, it would be better to only make users also depend on those libraries if they actually use them.

**Comment by plusCubed** [comment]
http://stackoverflow.com/questions/25345804/optional-gradle-dependencies-for-maven-libraries - don't know if this is possible with jitpack's release

**Comment by afollestad** [comment]
@plusCubed just saw that actually, didn't we do something with RecyclerView in Material Dialogs?

**Comment by afollestad** [comment]
Not sure if we still do, but we did at one point

**Comment by plusCubed** [comment]
@afollestad I don't recall doing such with the library... maybe just my memory though. I am finding a few plugins around for optional deps, but they all seem to just work with maven release.

**Comment by plusCubed** [comment]
Aha, just remembered that this is a thing in the Evernote job scheduling library I'm using for Anticipate - https://github.com/evernote/android-job - with play services. It seems to just use `provided` instead of `compile`. Don't know if that'll work.

**Comment by Jawnnypoo** [comment]
Yes, the library you are talking about seems to do it correctly using `provided`. You can see in this file, the are checking to see if the app has provided the dependency:
https://github.com/evernote/android-job/blob/1d5a3ab2c53e8f976aba905f4e8f183b48438586/library/src/main/java/com/evernote/android/job/util/GcmAvailableHelper.java

So basically, the code you are looking for is this:
```java
static {
        boolean gcmInClasspath;
        try {
            Class.forName("com.google.android.gms.gcm.GcmNetworkManager");
            gcmInClasspath = true;
        } catch (Throwable t) {
            gcmInClasspath = false;
        }
        GCM_IN_CLASSPATH = gcmInClasspath;
    }
```
so that you could do runtime checks to make sure the app is providing the dependency, and throw a useful exception if they are not.

**Comment by afollestad** [comment]
@Jawnnypoo more useful information from you 😁 thanks! I'll look into implementing this later today.

**Comment by afollestad** [comment]
https://github.com/afollestad/app-theme-engine/releases/tag/0.7.5
