### ISSUE TITLE
A way to ignore Toolbar overflows (e.g. using ate_ignore?)

### ISSUE THREAD

**Issue by julian200601** [afollestad/app-theme-engine#65]
Toolbar's overflow icon is always tinted even if it or a parent has the "ate_ignore" tag because the tint is applied to all toolbar overflow icons in the Activity. I post this as issue because I have no idea of an alternative way to to tint it.

**Comment by afollestad** [comment]
This won't be able to be done through tags, since the code doesn't actually use the `Toolbar`'s themselves to apply tinting. It's done through this: https://github.com/afollestad/app-theme-engine/blob/master/library/src/main/java/com/afollestad/appthemeengine/util/Util.java#L97

So it might be more practical to have a customizer or something which can disable overflow tinting on a per-Activity basis or something.

**Comment by julian200601** [comment]
@afollestad That's what I meant. Would it be possible to have for example an ATEOverflowItem to use in a menu resource which was just a Menuitem using ic_more_vert as standard where key, tinting y/n and default color are provided as styleable? I'll try that out tomorrow

**Comment by afollestad** [comment]
I'd rather avoid that too, that's a lot of logic to manually add and keep up to date over time.

**Comment by julian200601** [comment]
@afollestad Not sure what you mean
